### ISSUE TITLE
Icons on employee pages don't match

### ISSUE THREAD

**Issue by oliviag** [praytell/dotcom#4]
pick some cute ones!

![screen shot 2016-05-24 at 6 10 06 pm](https://cloud.githubusercontent.com/assets/1513332/15521649/d730a73a-21da-11e6-8530-a7c3fb81face.png)

**Comment by jonpraytell** [comment]
These are the 2 icon sets we use:
http://ionicons.com/
http://themes-pixeden.com/font-demos/7-stroke/index.html

<i class="icon ion-#####">

<i class="icon pe-7s-#####">
