### ISSUE TITLE
Line up social icons

### ISSUE THREAD

**Issue by oliviag** [praytell/dotcom#8]
It bothers me that linkedin seems a few px below the others

![screen shot 2016-05-24 at 6 12 46 pm](https://cloud.githubusercontent.com/assets/1513332/15521708/298b884c-21db-11e6-8498-3a4964c34194.png)

**Comment by gabe-sch9** [comment]
Just extensively checked it out and eventually discovered that its aligned along with the others on the bottom, just looks different. Maybe we could edit the ElegantIcons font? It also looks a little better in between fb and instagram
